---
name: juiceshop

networks: # docker network create external
  external:
    name: external
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: external
    external: true

services:
  juiceshop:
    container_name: js-app
    image: ghcr.io/mighty-muffin/juice-shop:latest
    restart: unless-stopped
    networks:
      - external
    ports:
      - 3000:3000
