---
name: whoami

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:
  whoami:
    container_name: whoami
    image: docker.io/traefik/whoami:v1.10
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - USERNAME="superuser"
      - PASSWORD="superuser"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local.mighty-muffin.io`)"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
